//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18213
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleDA.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BleDA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send notification.
        /// </summary>
        internal static string ActionNotification {
            get {
                return ResourceManager.GetString("ActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Manage windows service.
        /// </summary>
        internal static string ActionService {
            get {
                return ResourceManager.GetString("ActionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start program.
        /// </summary>
        internal static string ActionStart {
            get {
                return ResourceManager.GetString("ActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stop program.
        /// </summary>
        internal static string ActionStop {
            get {
                return ResourceManager.GetString("ActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alignment completed..
        /// </summary>
        internal static string MsgAlignmentCompleted {
            get {
                return ResourceManager.GetString("MsgAlignmentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alignment failed..
        /// </summary>
        internal static string MsgAlignmentFailed {
            get {
                return ResourceManager.GetString("MsgAlignmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alignment started. Please don&apos;t move..
        /// </summary>
        internal static string MsgAlignmentStarted {
            get {
                return ResourceManager.GetString("MsgAlignmentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apply settings failure..
        /// </summary>
        internal static string MsgApplySettingsFailure {
            get {
                return ResourceManager.GetString("MsgApplySettingsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm your position?.
        /// </summary>
        internal static string MsgAskConfirmation {
            get {
                return ResourceManager.GetString("MsgAskConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Better context found..
        /// </summary>
        internal static string MsgBetterContext {
            get {
                return ResourceManager.GetString("MsgBetterContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Context updated with new data..
        /// </summary>
        internal static string MsgContexUpdated {
            get {
                return ResourceManager.GetString("MsgContexUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AttiLA is running..
        /// </summary>
        internal static string MsgPreviousContext {
            get {
                return ResourceManager.GetString("MsgPreviousContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AttiLA has been awakened..
        /// </summary>
        internal static string MsgServiceAwake {
            get {
                return ResourceManager.GetString("MsgServiceAwake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AttiLA will be sleepy until the next localization request..
        /// </summary>
        internal static string MsgServiceSleeping {
            get {
                return ResourceManager.GetString("MsgServiceSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tracking start failure..
        /// </summary>
        internal static string MsgTrackingStartFailure {
            get {
                return ResourceManager.GetString("MsgTrackingStartFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BleDA Error.
        /// </summary>
        internal static string PopupError {
            get {
                return ResourceManager.GetString("PopupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BleDA Info.
        /// </summary>
        internal static string PopupInfo {
            get {
                return ResourceManager.GetString("PopupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BleDA Warning.
        /// </summary>
        internal static string PopupWarning {
            get {
                return ResourceManager.GetString("PopupWarning", resourceCulture);
            }
        }
    }
}
