//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BleDA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BleDA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send notification.
        /// </summary>
        internal static string ActionNotification {
            get {
                return ResourceManager.GetString("ActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage windows service.
        /// </summary>
        internal static string ActionService {
            get {
                return ResourceManager.GetString("ActionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start program.
        /// </summary>
        internal static string ActionStart {
            get {
                return ResourceManager.GetString("ActionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop program.
        /// </summary>
        internal static string ActionStop {
            get {
                return ResourceManager.GetString("ActionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment completed..
        /// </summary>
        internal static string MsgAlignmentCompleted {
            get {
                return ResourceManager.GetString("MsgAlignmentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment started. Please don&apos;t move..
        /// </summary>
        internal static string MsgAlignmentStarted {
            get {
                return ResourceManager.GetString("MsgAlignmentStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply settings failure..
        /// </summary>
        internal static string MsgApplySettingsFailure {
            get {
                return ResourceManager.GetString("MsgApplySettingsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking start failure..
        /// </summary>
        internal static string MsgTrackingStartFailure {
            get {
                return ResourceManager.GetString("MsgTrackingStartFailure", resourceCulture);
            }
        }
    }
}
